### ISSUE TITLE
issue with train_encdec.py

### ISSUE THREAD

**Issue by Yashaswini2039** [liren2515/DrapeNet#22]
As i was trying to train the model i encountered an error with "python train_encdec.py  # add </path/to/run/cfg/file> to restore training"

Traceback (most recent call last):
  File "train_encdec.py", line 7, in <module>
    from trainers.encdec import EncoderDecoderTrainer
  File "/workspace/DrapeNet/encdec/../trainers/encdec.py", line 14, in <module>
    from models.dgcnn import Dgcnn
  File "/workspace/DrapeNet/encdec/../models/dgcnn.py", line 5, in <module>
    from pytorch3d.ops import knn_gather, knn_points
  File "/workspace/DrapeNet/.venv/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/workspace/DrapeNet/.venv/lib/python3.8/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

the libraries where downloaded as suggested but still getting the error 

can u help!!!

**Comment by liren2515** [comment]
I think this error comes from the incompatible of the library of your environment. I don't know the exact idea about how to solve it. But I think you need to try to reinstall pytorch3d. There are some guides from pytorch3d telling you how to install it in different ways. You can try them.

**Comment by Yashaswini2039** [comment]
i was able to solve it by making few changes in the code....

Thank you 👍
